// ============================================================
// ASTRIX285 — Main JavaScript
// ============================================================

const TWITCH_CHANNEL = 'astrix285x';
const FB_PAGE        = 'https://www.facebook.com/xASTRIX285x';

// ── NAV ACTIVE STATE ────────────────────────────────────────
function setActiveNav() {
  const path = window.location.pathname;
  document.querySelectorAll('.nav-links a').forEach(link => {
    link.classList.remove('active');
    const href = link.getAttribute('href');
    if (path.endsWith(href) || (path === '/' && href === 'index.html') ||
        (path.endsWith('/') && href === 'index.html')) {
      link.classList.add('active');
    }
  });
}

// ── SCROLL REVEAL ───────────────────────────────────────────
function setupReveal() {
  const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) entry.target.classList.add('visible');
    });
  }, { threshold: 0.15 });
  document.querySelectorAll('.reveal').forEach(el => observer.observe(el));
}

// ── STREAM EMBED SCROLL EXPANSION ───────────────────────────
function setupStreamExpansion() {
  const embed = document.querySelector('.stream-live-embed');
  if (!embed) return;

  function onScroll() {
    const rect = embed.getBoundingClientRect();
    const winH  = window.innerHeight;
    const distFromCenter = Math.abs((rect.top + rect.height / 2) - winH / 2);
    const maxDist = winH / 2 + rect.height / 2;
    const progress = Math.max(0, 1 - distFromCenter / (maxDist * 0.6));
    const scale = 0.6 + (0.4 * progress);
    embed.style.transform = `scaleX(${scale})`;
    if (scale >= 0.99) embed.classList.add('expanded');
    else embed.classList.remove('expanded');
  }

  window.addEventListener('scroll', onScroll, { passive: true });
  onScroll();
}

// ── SET OFFLINE VOD STATE ────────────────────────────────────
function setOfflineVod(data) {
  const vodEmbed    = document.getElementById('vodEmbed');
  const vodTitle    = document.getElementById('vodTitle');
  const vodFbLink   = document.getElementById('vodFbLink');
  const vodTwLink   = document.getElementById('vodTwLink');
  const vodSection  = document.getElementById('vodSection');
  const vodFallback = document.getElementById('vodFallback');

  if (data.vod_id && vodEmbed) {
    vodEmbed.src = `https://player.twitch.tv/?video=${data.vod_id}&parent=astrixparadox.com&parent=www.astrixparadox.com&autoplay=false&muted=true`;
    // Hide crimson glow/scanlines when VOD is active
    const offlineFull = document.getElementById('streamOffline');
    if (offlineFull) offlineFull.classList.add('has-vod');

    if (vodTitle)  vodTitle.textContent = data.vod_title || 'Latest Stream';
    if (vodTwLink) vodTwLink.href       = data.vod_url   || `https://twitch.tv/${TWITCH_CHANNEL}`;

    if (vodFbLink) {
      const fbShareUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(data.vod_url || '')}`;
      vodFbLink.href = fbShareUrl;
    }

    if (vodSection)  vodSection.style.display  = 'block';
    if (vodFallback) vodFallback.style.display = 'none';
  } else {
    if (vodSection)  vodSection.style.display  = 'none';
    if (vodFallback) vodFallback.style.display = 'block';
  }
}

// ── TWITCH LIVE CHECK ───────────────────────────────────────
async function checkTwitchLive() {
  const navDot    = document.querySelector('.nav-live-dot');
  const navText   = document.querySelector('.nav-live-text');
  const offlineEl = document.getElementById('streamOffline');
  const liveEl    = document.getElementById('streamLive');

  try {
    // Reads the safe JSON file generated by GitHub Action — no secrets in code
    const res  = await fetch('/twitch-status.json?t=' + Date.now());
    if (!res.ok) throw new Error('Status file not found');
    const data = await res.json();

    if (data.live) {
      if (navDot)  navDot.classList.add('live');
      if (navText) navText.textContent = '🔴 LIVE NOW';
      if (liveEl)    liveEl.style.display    = 'block';
      if (offlineEl) offlineEl.style.display = 'none';
      document.title = `🔴 LIVE — ${data.game || 'Gaming'} | ASTRIX285`;
      setupStreamExpansion();
    } else {
      if (navDot)    navDot.classList.remove('live');
      if (navText)   navText.textContent = 'OFFLINE';
      if (offlineEl) offlineEl.style.display = 'flex';
      if (liveEl)    liveEl.style.display    = 'none';
      setOfflineVod(data);
    }

  } catch (e) {
    // Fallback to offline state if JSON not yet generated
    if (navDot)    navDot.classList.remove('live');
    if (navText)   navText.textContent = 'OFFLINE';
    if (offlineEl) offlineEl.style.display = 'flex';
    if (liveEl)    liveEl.style.display    = 'none';
    const vodFallback = document.getElementById('vodFallback');
    if (vodFallback) vodFallback.style.display = 'block';
  }
}

// ── MOBILE NAV ──────────────────────────────────────────────
function setupMobileNav() {
  const toggle = document.querySelector('.nav-toggle');
  const links  = document.querySelector('.nav-links');
  if (!toggle || !links) return;

  toggle.addEventListener('click', () => {
    links.classList.toggle('open');
    toggle.classList.toggle('open');
  });

  // Close menu when a link is clicked
  links.querySelectorAll('a').forEach(a => {
    a.addEventListener('click', () => {
      links.classList.remove('open');
      toggle.classList.remove('open');
    });
  });

  // Close menu when clicking outside
  document.addEventListener('click', (e) => {
    if (!toggle.contains(e.target) && !links.contains(e.target)) {
      links.classList.remove('open');
      toggle.classList.remove('open');
    }
  });
}

// ── HERO VIDEO SPEED ─────────────────────────────────────────
function setupHeroVideo() {
  const video = document.getElementById('heroBg');
  if (!video) return;
  video.addEventListener('loadedmetadata', () => { video.playbackRate = 0.5; });
  if (video.readyState >= 1) video.playbackRate = 0.5;
}

// ── INIT ────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
  setActiveNav();
  setupReveal();
  setupMobileNav();
  setupHeroVideo();
  checkTwitchLive();
});
