from pathlib import Path
engine=Path('astrix-app/pages/guardian-workspace-v2/guardian-paradox-engine.mjs')
text=engine.read_text()
text=text.replace('function traitEvidence(nodes,curatedEntries){','function traitEvidence(nodes,curatedEntries,runtimeLoop=[]){',1)
text=text.replace("const texts = [item?.description, item?.directionEvidence?.description].map(clean).filter(Boolean);","const texts = [item?.directionEvidence?.description].map(clean).filter(Boolean);",1)
old="""        const curatedAB=curatedDirection(curatedEntries,nodes,a,b,effect);\n        const curatedBA=curatedDirection(curatedEntries,nodes,b,a,effect);\n        const directionAB=a.directionEffects.outputs.includes(effect)&&b.directionEffects.inputs.includes(effect);\n        const directionBA=b.directionEffects.outputs.includes(effect)&&a.directionEffects.inputs.includes(effect);\n        const buffAB=a.traitEffects.buffOutputs.includes(effect)&&b.traitEffects.mentions.includes(effect)&&!b.traitEffects.buffOutputs.includes(effect);\n        const buffBA=b.traitEffects.buffOutputs.includes(effect)&&a.traitEffects.mentions.includes(effect)&&!a.traitEffects.buffOutputs.includes(effect);\n        const anchorAB=(a.directionEvidence?.description||b.directionEvidence?.description)?'bungie-direction-description':'runtime-description-direction';\n        const anchorBA=(b.directionEvidence?.description||a.directionEvidence?.description)?'bungie-direction-description':'runtime-description-direction';\n\n        if(directionAB)addLink(a,effect,b,anchorAB);\n        if(directionBA)addLink(b,effect,a,anchorBA);\n        if(curatedAB)addLink(a,effect,b,'curated-fixture-data');\n        if(curatedBA)addLink(b,effect,a,'curated-fixture-data');\n        if(!directionAB&&!curatedAB&&buffAB)addLink(a,effect,b,'keywords.buffs producer signal');\n        if(!directionBA&&!curatedBA&&buffBA)addLink(b,effect,a,'keywords.buffs producer signal');\n\n        const directed=directionAB||directionBA||curatedAB||curatedBA||buffAB||buffBA;"""
new="""        const curatedAB=curatedDirection(curatedEntries,nodes,a,b,effect);\n        const curatedBA=curatedDirection(curatedEntries,nodes,b,a,effect);\n        const runtimeAB=runtimeLoop.some(link=>Number(link?.from?.hash)===Number(a.hash)&&canonEffect(link?.output)===effect&&Number(link?.to?.hash)===Number(b.hash));\n        const runtimeBA=runtimeLoop.some(link=>Number(link?.from?.hash)===Number(b.hash)&&canonEffect(link?.output)===effect&&Number(link?.to?.hash)===Number(a.hash));\n        const directionAB=a.directionEffects.outputs.includes(effect)&&b.directionEffects.inputs.includes(effect);\n        const directionBA=b.directionEffects.outputs.includes(effect)&&a.directionEffects.inputs.includes(effect);\n        const buffAB=a.traitEffects.buffOutputs.includes(effect)&&b.traitEffects.mentions.includes(effect)&&!b.traitEffects.buffOutputs.includes(effect);\n        const buffBA=b.traitEffects.buffOutputs.includes(effect)&&a.traitEffects.mentions.includes(effect)&&!a.traitEffects.buffOutputs.includes(effect);\n\n        if(runtimeAB)addLink(a,effect,b,'runtime-description-parsing');\n        if(runtimeBA)addLink(b,effect,a,'runtime-description-parsing');\n        if(curatedAB)addLink(a,effect,b,'curated-fixture-data');\n        if(curatedBA)addLink(b,effect,a,'curated-fixture-data');\n        if(directionAB&&!runtimeBA&&!curatedBA)addLink(a,effect,b,'bungie-direction-description');\n        if(directionBA&&!runtimeAB&&!curatedAB)addLink(b,effect,a,'bungie-direction-description');\n        if(buffAB&&!runtimeBA&&!curatedBA&&!directionBA)addLink(a,effect,b,'keywords.buffs producer signal');\n        if(buffBA&&!runtimeAB&&!curatedAB&&!directionAB)addLink(b,effect,a,'keywords.buffs producer signal');\n\n        const directed=runtimeAB||runtimeBA||directionAB||directionBA||curatedAB||curatedBA||buffAB||buffBA;"""
assert old in text
text=text.replace(old,new,1)
text=text.replace('const trait = traitEvidence(nodes,build.synergyChains);','const trait = traitEvidence(nodes,build.synergyChains,runtimeLoop);',1)
engine.write_text(text)
