from pathlib import Path
engine=Path('astrix-app/pages/guardian-workspace-v2/guardian-paradox-engine.mjs')
text=engine.read_text()
text=text.replace('function traitEvidence(nodes,curatedEntries){','function traitEvidence(nodes,curatedEntries,runtimeLoop=[]){',1)
text=text.replace("const texts = [item?.description, item?.directionEvidence?.description].map(clean).filter(Boolean);","const texts = [item?.directionEvidence?.description].map(clean).filter(Boolean);",1)
old="""        const curatedAB=curatedDirection(curatedEntries,nodes,a,b,effect);\n        const curatedBA=curatedDirection(curatedEntries,nodes,b,a,effect);\n        const directionAB=a.directionEffects.outputs.includes(effect)&&b.directionEffects.inputs.includes(effect);\n        const directionBA=b.directionEffects.outputs.includes(effect)&&a.directionEffects.inputs.includes(effect);\n        const buffAB=a.traitEffects.buffOutputs.includes(effect)&&b.traitEffects.mentions.includes(effect)&&!b.traitEffects.buffOutputs.includes(effect);\n        const buffBA=b.traitEffects.buffOutputs.includes(effect)&&a.traitEffects.mentions.includes(effect)&&!a.traitEffects.buffOutputs.includes(effect);\n        const anchorAB=(a.directionEvidence?.description||b.directionEvidence?.description)?'bungie-direction-description':'runtime-description-direction';\n        const anchorBA=(b.directionEvidence?.description||a.directionEvidence?.description)?'bungie-direction-description':'runtime-description-direction';\n\n        if(directionAB)addLink(a,effect,b,anchorAB);\n        if(directionBA)addLink(b,effect,a,anchorBA);\n        if(curatedAB)addLink(a,effect,b,'curated-fixture-data');\n        if(curatedBA)addLink(b,effect,a,'curated-fixture-data');\n        if(!directionAB&&!curatedAB&&buffAB)addLink(a,effect,b,'keywords.buffs producer signal');\n        if(!directionBA&&!curatedBA&&buffBA)addLink(b,effect,a,'keywords.buffs producer signal');\n\n        const directed=directionAB||directionBA||curatedAB||curatedBA||buffAB||buffBA;"""
new="""        const curatedAB=curatedDirection(curatedEntries,nodes,a,b,effect);\n        const curatedBA=curatedDirection(curatedEntries,nodes,b,a,effect);\n        const runtimeAB=runtimeLoop.some(link=>Number(link?.from?.hash)===Number(a.hash)&&canonEffect(link?.output)===effect&&Number(link?.to?.hash)===Number(b.hash));\n        const runtimeBA=runtimeLoop.some(link=>Number(link?.from?.hash)===Number(b.hash)&&canonEffect(link?.output)===effect&&Number(link?.to?.hash)===Number(a.hash));\n        const directionAB=a.directionEffects.outputs.includes(effect)&&b.directionEffects.inputs.includes(effect);\n        const directionBA=b.directionEffects.outputs.includes(effect)&&a.directionEffects.inputs.includes(effect);\n        const buffAB=a.traitEffects.buffOutputs.includes(effect)&&b.traitEffects.mentions.includes(effect)&&!b.traitEffects.buffOutputs.includes(effect);\n        const buffBA=b.traitEffects.buffOutputs.includes(effect)&&a.traitEffects.mentions.includes(effect)&&!a.traitEffects.buffOutputs.includes(effect);\n\n        if(runtimeAB)addLink(a,effect,b,'runtime-description-parsing');\n        if(runtimeBA)addLink(b,effect,a,'runtime-description-parsing');\n        if(curatedAB)addLink(a,effect,b,'curated-fixture-data');\n        if(curatedBA)addLink(b,effect,a,'curated-fixture-data');\n        if(directionAB&&!runtimeBA&&!curatedBA)addLink(a,effect,b,'bungie-direction-description');\n        if(directionBA&&!runtimeAB&&!curatedAB)addLink(b,effect,a,'bungie-direction-description');\n        if(buffAB&&!runtimeBA&&!curatedBA&&!directionBA)addLink(a,effect,b,'keywords.buffs producer signal');\n        if(buffBA&&!runtimeAB&&!curatedAB&&!directionAB)addLink(b,effect,a,'keywords.buffs producer signal');\n\n        const directed=runtimeAB||runtimeBA||directionAB||directionBA||curatedAB||curatedBA||buffAB||buffBA;"""
assert old in text
text=text.replace(old,new,1)
text=text.replace('const trait = traitEvidence(nodes,build.synergyChains);','const trait = traitEvidence(nodes,build.synergyChains,runtimeLoop);',1)
engine.write_text(text)

test=Path('astrix-app/tools/test-pf-beta-04-subclass-fallback.mjs')
t=test.read_text()
old="""  const keyMap=new Map();\n  for(const link of result.buildLoop){\n    const key=`${Number(link.from?.hash)}|${link.output}|${Number(link.to?.hash)}`;\n    keyMap.set(key,(keyMap.get(key)??0)+1);\n    const reverse=`${Number(link.to?.hash)}|${link.output}|${Number(link.from?.hash)}`;\n    if(keyMap.has(reverse))suspicious.push({fixtureId:fixture.fixtureId,type:'symmetric',link:link.chain,reverse});\n  }\n  for(const [key,count] of keyMap){\n    if(count>1)suspicious.push({fixtureId:fixture.fixtureId,type:'duplicate',key,count});\n  }"""
new="""  const keyRows=new Map();\n  const keyCounts=new Map();\n  const isTraitOnly=link=>{\n    const sources=(link?.evidenceSources??[]).map(row=>row?.source).filter(Boolean);\n    return String(link?.source)==='runtime-traitid-parsing' || (sources.length>0&&sources.every(source=>source==='runtime-traitid-parsing'));\n  };\n  for(const link of result.buildLoop){\n    const key=`${Number(link.from?.hash)}|${link.output}|${Number(link.to?.hash)}`;\n    const reverse=`${Number(link.to?.hash)}|${link.output}|${Number(link.from?.hash)}`;\n    const reverseLink=keyRows.get(reverse);\n    if(reverseLink&&(isTraitOnly(link)||isTraitOnly(reverseLink))){\n      suspicious.push({fixtureId:fixture.fixtureId,type:'trait-created-symmetric',link:link.chain,reverse:reverseLink.chain});\n    }\n    keyRows.set(key,link);\n    keyCounts.set(key,(keyCounts.get(key)??0)+1);\n  }\n  for(const [key,count] of keyCounts){\n    if(count>1)suspicious.push({fixtureId:fixture.fixtureId,type:'duplicate',key,count});\n  }"""
assert old in t
t=t.replace(old,new,1)
test.write_text(t)
