#!/usr/bin/env python3
"""Build the small, official Bungie identity cache used by loadout cards.

The player profile stores nameHash, iconHash and colorHash.  Those values are
only displayable after resolving them against Bungie's matching manifest
definitions.  This script downloads those three definition tables and writes
an ES module so the browser never invents a loadout name, icon or colour.
"""

from __future__ import annotations

import json
import urllib.request
from pathlib import Path
from typing import Any


BUNGIE_ROOT = "https://www.bungie.net"
MANIFEST_URL = f"{BUNGIE_ROOT}/Platform/Destiny2/Manifest/"
USER_AGENT = {"User-Agent": "ASTRIX-Paradox-Forge/1.0"}
OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "pages"
    / "guardian-workspace-v2"
    / "guardian-loadout-definitions.mjs"
)
COMPONENTS = {
    "names": "DestinyLoadoutNameDefinition",
    "icons": "DestinyLoadoutIconDefinition",
    "colors": "DestinyLoadoutColorDefinition",
}


def fetch_json(url: str) -> dict[str, Any]:
    request = urllib.request.Request(url, headers=USER_AGENT)
    with urllib.request.urlopen(request, timeout=60) as response:
        payload = json.loads(response.read().decode("utf-8"))
    if isinstance(payload, dict) and payload.get("ErrorCode") not in (None, 1):
        raise RuntimeError(payload.get("Message") or "Bungie API error")
    return payload


def compact(component: str, rows: dict[str, Any]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for raw_hash, row in rows.items():
        if not isinstance(row, dict) or row.get("redacted") or row.get("blacklisted"):
            continue
        if component == "names":
            value = {"name": str(row.get("name") or "")}
        elif component == "icons":
            value = {"iconImagePath": str(row.get("iconImagePath") or "")}
        else:
            value = {"colorImagePath": str(row.get("colorImagePath") or "")}
        result[str(raw_hash)] = value
    return result


def main() -> int:
    manifest = fetch_json(MANIFEST_URL)["Response"]
    paths = manifest["jsonWorldComponentContentPaths"]["en"]
    definitions: dict[str, Any] = {}

    for key, manifest_name in COMPONENTS.items():
        path = paths.get(manifest_name)
        if not path:
            raise RuntimeError(f"Bungie manifest omitted {manifest_name}")
        definitions[key] = compact(key, fetch_json(f"{BUNGIE_ROOT}{path}"))

    source = {
        "manifestVersion": str(manifest.get("version") or "unknown"),
        "source": "bungie-current-manifest",
        **definitions,
    }
    module = (
        "/* Generated by build-guardian-loadout-definitions.py. Do not hand edit. */\n"
        f"const LOADOUT_DEFINITIONS={json.dumps(source, separators=(',', ':'), ensure_ascii=False)};\n"
        "export {LOADOUT_DEFINITIONS};\n"
    )
    OUTPUT.write_text(module, encoding="utf-8")
    print(f"WROTE={OUTPUT}")
    print(f"MANIFEST_VERSION={source['manifestVersion']}")
    for key in COMPONENTS:
        print(f"{key.upper()}={len(definitions[key])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
